GET http://localhost:3002/api/blogs

###
GET http://localhost:3002/api/blogs/6534bea004778a3c70ac5fd8


###
POST http://localhost:3002/api/blogs
Content-Type: application/json

{
  "title": "Test title1",
  "author": "Test author",
  "url": "www.test.com",
  "likes": 123
}

###
POST http://localhost:3002/api/blogs
Content-Type: application/json

{
  "title": "Test title1",
  "author": "Test author",
  
  "likes": 123
}

###
DELETE http://localhost:3002/api/blogs/6534bea004778a3c70ac5fd8

###
PUT http://localhost:3002/api/blogs/6534bea604778a3c70ac5fdb
Content-Type: application/json

{
  "title": "Test PUT",
  "author": "Test author",
  "url": "www.test.com",
  "likes": 123
}

###
#Get all users
GET http://localhost:3002/api/users

###
# Create a user
POST http://localhost:3002/api/users
Content-Type: application/json

{
  "username": "user2",
  "password": "pass2",
  "name": "NameOfUser"
}